server:
  port: 8080
  servlet:
    context-path: /weather-station/v1/

#management:
#  endpoint:
#    health:
#      show-components: always
#  endpoints:
#    web:
#      exposure:
#      include: *

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

#logging:
#  path: .
#  level:
#    root: info
#    org:
#      springframework:
#        web: info