version: '3'
services:
  redis:
    container_name: redis
    image: redis:5.0.4
    command: redis-server
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: 500m
  db:
    container_name: 'db-weather-station'
    image: mysql:8.0
    restart: 'always'
    environment:
      MYSQL_DATABASE: weather
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-weather-station:/var/lib/mysql
volumes:
  db-weather-station: